name: Build & Release JAR
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      id: checkout
    - name: Set up JDK 1.8
      id: setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get the Version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Set the Version
      id: set_version
      run: ./mvnw -B versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }} --file pom.xml
    - name: Package JARs
      id: build_maven
      run: ./mvnw -B package --file pom.xml -DskipTests
