name: Build & Release JAR
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      id: setup_java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: bintray-letsrokk-github
        server-username: BITRAY_USERNAME
        server-password: BINTRAY_API_KEY
    - name: Get Version from Tag Name
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Set Version for Project
      id: set_version
      run: ./mvnw -B versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }} --file pom.xml
    - name: Deploy JARs
      id: deploy_bintray
      run: ./mvnw -B package deploy --file pom.xml -DskipTests
      env:
        BITRAY_USERNAME: ${{ secrets.BITRAY_USERNAME }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
